## **Import the libraries**

In [94]:
import numpy as np
import pandas as pd
import tensorflow as tf

## **Part 1 - Data Preprocessing**

### **Importing the dataset**

In [95]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [96]:
y

array([1, 0, 1, ..., 1, 1, 0])

## **Encoding Categorical Data**

In [97]:
# Label Encoding Gender Column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [98]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [99]:
# One Hot Encoding for Geography Column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

## **Splitting the dataset into the training set and test set**

In [100]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [101]:
X_test[5,:]

array([0.0, 0.0, 1.0, 670, 0, 57, 3, 175575.95, 2, 1, 0, 99061.75],
      dtype=object)

In [102]:
y_test[5]

1

## **Feature Scaling**

In [103]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [104]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [105]:
X_test

array([[-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  1.61255917]])

## **Part 2 - Building ANN**

### **Initializing the ANN**

In [106]:
ann = tf.keras.models.Sequential()

### **Adding input layer and the first hidden layer**

In [107]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### **Adding second layer**

In [108]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### **Adding output layer**

In [109]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## **Part 3 - Training the ANN**

### **Compiling the ANN**

In [110]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

### **Training the ANN on the training set**

In [111]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6476 - accuracy: 0.6494
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4728 - accuracy: 0.7993
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4478 - accuracy: 0.8010
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4362 - accuracy: 0.8077
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4306 - accuracy: 0.8109
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4269 - accuracy: 0.8105
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4231 - accuracy: 0.8154
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4175 - accuracy: 0.8190
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4068 - accuracy: 0.8263
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3928 - accura

### **Predicting the test set result**

In [112]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### **Making confusion matrix**

In [113]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1501   94]
 [ 187  218]]


In [114]:
accuracy_score(y_test, y_pred)

0.8595

### **Making single prediction**

In [115]:
# 1.0, 0.0, 0.0, 523, 0, 40, 2, 102967.41, 1, 1, 0, 128702.1
print(ann.predict(sc.transform([[0.0, 0.0, 1.0, 670, 0, 57, 3, 175575.95, 2, 1, 0, 99061.75]])))

1/1 [==============================] - 0s 31ms/step
[[0.9727903]]


In [117]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))> 0.5)

1/1 [==============================] - 0s 21ms/step
[[False]]
